
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 16 03:41:51 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 47;
  public static final int CONST = 8;
  public static final int GE = 36;
  public static final int NAMESPACE = 4;
  public static final int LPAREN = 18;
  public static final int SEMI = 26;
  public static final int CONTINUE = 11;
  public static final int FOR = 17;
  public static final int STATIC = 7;
  public static final int RPAREN = 19;
  public static final int AND = 39;
  public static final int LT = 37;
  public static final int OR = 40;
  public static final int BOOL = 46;
  public static final int COMMA = 25;
  public static final int CLASS = 3;
  public static final int INC = 42;
  public static final int DIV = 31;
  public static final int NUM = 44;
  public static final int ASSIGN = 41;
  public static final int IF = 15;
  public static final int DOT = 24;
  public static final int LE = 38;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int ADD = 28;
  public static final int MOD = 32;
  public static final int IDENT = 45;
  public static final int BREAK = 10;
  public static final int VOID = 6;
  public static final int EQ = 33;
  public static final int LBRACK = 22;
  public static final int LBRACE = 20;
  public static final int ELSE = 16;
  public static final int READ = 13;
  public static final int RBRACK = 23;
  public static final int SCOPE = 27;
  public static final int RBRACE = 21;
  public static final int EXTENDS = 5;
  public static final int PROG = 2;
  public static final int NE = 34;
  public static final int DEC = 43;
  public static final int GT = 35;
  public static final int SUB = 29;
  public static final int PRINT = 12;
}

